import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useRef } from "react";
import Featuredarticle1 from "../../public/images/articles/AssistantBot.png";
import Featuredarticle2 from "../../public/images/articles/FlaskApp.jpg";
import article1 from "../../public/images/articles/Article1.jpg";
import article2 from "../../public/images/articles/Article2.jpg";
import article3 from "../../public/images/articles/Article3.webp";
import article4 from "../../public/images/articles/Article4.jpg";
import { motion, useMotionValue } from "framer-motion";
import TransitionEffect from "@/components/TransitionEffect";

const FramerImage = motion(Image);

const FeaturedArticles = ({ img, title, time, summary, link }) => {
  return (
    <li className="col-span-1 w-full p-4 bg-light border border-solid border-dark rounded-2xl relative dark:bg-dark dark:border-light">
      <div
        className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark
      rounded-br-3xl "
      />
      <Link
        href={link}
        target="_blank"
        className="w-1/2 cursor-pointer overflow-hidden rounded-lg"
      >
        <FramerImage
          src={img}
          alt={title}
          className="w-full h-auto"
          whileHover={{ scale: 1.05 }}
          transition={{ duration: 0.2 }}
          priority
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
        />
      </Link>
      <Link href={link} target="_blank">
        <h2 className="capitalize text-2xl font-bold my-2 mt-4 hover:underline xs:text-lg">
          {title}
        </h2>
      </Link>
      <p className="text-sm mb-2">{summary}</p>
      <span className="text-primary font-semibold dark:text-primaryDark">
        {time}
      </span>
    </li>
  );
};

const MovingImg = ({ title, img, link }) => {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const ImgRef = useRef(null);

  function handleMouse(event) {
    ImgRef.current.style.display = "inline-block";
    x.set(event.pageX);
    y.set(-10);
  }

  function handleMouseLeave(event) {
    ImgRef.current.style.display = "none";
    x.set(0);
    y.set(0);
  }
  return (
    <Link
      href={link}
      target="_blank"
      onMouseMove={handleMouse}
      onMouseLeave={handleMouseLeave}
    >
      <h2 className="capitalize text-xl font-semibold hover:underline">
        {title}
      </h2>
      <FramerImage
        style={{ x: x, y: y }}
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1, transition: { duration: 0.2 } }}
        ref={ImgRef}
        src={img}
        alt={title}
        className="z-10 w-96 h-auto hidden absolute rounded-lg md:!hidden"
      />
    </Link>
  );
};
const Article = ({ img, title, date, link }) => {
  return (
    <motion.li
      initial={{ y: 200 }}
      whileInView={{ y: 0, transition: { duration: 0.5, ease: "easeInOut" } }}
      className="w-full relative p-4 py-6 my-4 rounded-xl flex items-center justify-between
    bg-light text-dark first:mt-0 border border-solid border-dark border-r-4 border-b-4
    dark:border-light dark:bg-dark dark:text-light sm:flex-col"
    >
      <MovingImg title={title} img={img} link={link} />
      <span className="text-primary font-semibold pl-4 dark:text-primaryDark sm:self-start sm:pl-0 xs:text-sm">
        {date}
      </span>
    </motion.li>
  );
};

const articles = () => {
  return (
    <>
      <Head>
        <title>Mosin Inamdar | Articles Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="w-full mb-16 flex flex-col items-center justify-center dark:text-light">
        <Layout className="pt-16">
          <AnimatedText
            text="Words Can Change The World!"
            className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"
          />
          <ul className="grid grid-cols-2 gap-16 lg:gap-8 md:grid-cols-1 md:gap-y-16">
            <FeaturedArticles
              img={Featuredarticle1}
              title="Building Your Personal Assistant Website with OpenAI, NodeJS, and ReactJS"
              time="6 min read"
              summary="The blog discusses creating a personal assistant website using OpenAI, NodeJS, and ReactJS. 
              It outlines the steps to integrate OpenAI's capabilities into a web application, leveraging NodeJS for 
              backend development and ReactJS for frontend. This combination offers a powerful platform for building 
              intelligent virtual assistants."
              link="https://medium.com/@mosininamdar/building-your-personal-assistant-website-with-openai-nodejs-and-reactjs-d0c527555389"
            />
            <FeaturedArticles
              img={Featuredarticle2}
              title="How to make a Signup, Login and logout Route in flask app in 5 minutes"
              time="3 min read"
              summary="The blog provides a quick guide to implementing signup, login, and logout routes in a Flask app
              in just five minutes. It covers creating routes for user registration, authentication, and 
              session management, emphasizing simplicity and efficiency in setting up these essential functionalities 
              for web applications using Flask."
              link="https://medium.com/@mosininamdar/how-to-make-a-signup-login-and-logout-route-in-flask-app-in-5-minutes-f5c771f7a8f3"
            />
          </ul>
          <h2 className="font-bold text-4xl w-full text-center my-16 mt-32">
            All Articles
          </h2>
          <ul>
            <Article
              title="Building Your Own AI Assistant with OpenAI and Node.js: A Comprehensive Guide"
              date="Mar 8, 2024"
              img={article1}
              link="https://medium.com/@mosininamdar/building-your-own-ai-assistant-with-openai-and-node-js-a-comprehensive-guide-a47c6aea9c3a"
            />
            <Article
              title="Unveiling Sora: OpenAI’s Groundbreaking Video Generation Tool"
              date="Mar 4, 2024"
              img={article2}
              link="https://medium.com/@mosininamdar/unveiling-sora-openais-groundbreaking-video-generation-tool-78c77a873116"
            />
            <Article
              title="How To Integrating ChatGPT with Your React App in 5 Minutes"
              date="Mar 1, 2024"
              img={article3}
              link="https://medium.com/@mosininamdar/how-to-integrating-chatgpt-with-your-react-app-in-5-minutes-a-quick-and-easy-guide-9db4f7382086"
            />
            <Article
              title="A Deep Dive into Artificial Intelligence and Machine Learning"
              date="Nov 6, 2023"
              img={article4}
              link="https://medium.com/@mosininamdar18/exploring-the-frontiers-of-technology-a-deep-dive-into-artificial-intelligence-and-machine-c069f7e25ad6"
            />
          </ul>
        </Layout>
      </main>
    </>
  );
};

export default articles;
